version: "3.9"
services:
  es-server:
    container_name: es-server
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data:/usr/share/elasticsearch/data
    networks:
      - dev
      - prod
    environment:
      - node.name=es01
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    restart: always

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.13.4
    ports:
      - "5601:5601"
    networks:
      - dev
      - prod
    environment:
      - ELASTICSEARCH_HOSTS=http://es-server:9200
    restart: always

networks:
  elasticnet:
    name: elasticnet
  dev:
    name: dev
  prod:
    name: prod
